# .github/workflows/deploy.yml
name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Create deployment package
        run: |
          zip -r deploy.zip . -x "*.git*" "*.github*"
      
      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"
      
      - name: Upload to S3
        run: |
          BUCKET_NAME="elasticbeanstalk-test-$(aws sts get-caller-identity --query "Account" --output text)-${{ secrets.AWS_REGION }}"
          VERSION_LABEL="v2-${{ steps.timestamp.outputs.timestamp }}-${{ github.sha }}"
          aws s3 cp deploy.zip s3://$BUCKET_NAME/$VERSION_LABEL.zip
          echo "VERSION_LABEL=$VERSION_LABEL" >> $GITHUB_ENV
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
      
      - name: Create Application Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name eb-test-app \
            --version-label ${{ env.VERSION_LABEL }} \
            --description "Commit ${{ github.sha }}" \
            --source-bundle S3Bucket=${{ env.BUCKET_NAME }},S3Key=${{ env.VERSION_LABEL }}.zip \
            --process
      
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name eb-test-docker-env \
            --version-label ${{ env.VERSION_LABEL }}
